spring:
  #thymeleaf start
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    #使用宽松模式解析网页，默认使用严格的HTML5标准
    mode: LEGACYHTML5
    #content-type: text/html
  #thymeleaf end

  #spring.thymeleaf.content-type 弃用;改用下方的
  servlet:
    content-type: text/html
    mode: HTML5


  #热部署配置-开始
#  devtools:
#    restart:
#      #热部署生效
#      enabled: true
#      #设置重启的目录
#      additional-paths: resources/**,static/**,templates/**
#      #该目录下的内容修改不重启
#      exclude: data/**
  #热部署配置-结束
  security:
    basic:
      enabled: true
# 关闭 CONDITION EVALUATION DELTA
#logging.level.org.springframework.boot.autoconfigure: ERROR

